### ISSUE TITLE
Make Batch client work with PIDClientCredentials

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/PYHANDLE#13]
The PIDClientCredentials is a good class to conveniently cover all possible authentication cases and get the information either through function calls or from a JSON file.
The batch client has however its own methods. To use both clients transparently, the batch client should be able to work with PIDClientCredential instances as well (e.g. via a generic authenticate() method that takes a PIDClientCredentials instance as only parameter).

**Comment by TobiasWeigel** [comment]
One further issue may be that if private key authentication is to be used, it is logically nto required to provide a password in the credentials file. However, omitting a password will cause the credentials file read method to throw an error, complaining that without password, searchign will not be possible.
Suggested solution: modify credentials JSON read method so that possibility for searches is not checked if a specific flag parameter is given. Or make a subclass that is specific for the REST mode and only there the error will be thrown.

**Comment by SofianeB** [comment]
#17  resolves this.

**Comment by SofianeB** [comment]
First issue solved by #17 and create new issue for https://github.com/EUDAT-B2SAFE/PYHANDLE/issues/13#issuecomment-367399512
