### ISSUE TITLE
Is pyhandleclient.py superfluous?

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/PYHANDLE#14]
Seems to be a duplicate of handleclient.py but with less code. Is this a leftover from earlier implementation attempts?

https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/d1b0f2fbe186f47d6909362156a27c675930d675/pyhandle/pyhandleclient.py#L1

**Comment by SofianeB** [comment]
The pyhandleclient has been separated from the handlientclient to solve a circular import issue. The code can be optimized to avoid duplicate methods.

**Comment by TobiasWeigel** [comment]
OK, that explained it to me. Now I see that the concrete client classes inherit from this 'abstract' class and how that would create a circular dependency otherwise. Thanks!
