### ISSUE TITLE
handle_server_url from credentials file is not used properly

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/PYHANDLE#15]
If a credentials JSON file specifies a 'handle_server_url' param, this will be overwritten in the REST client's init method, even if the init method's own handle_server_url param is not set. A simple "if handle_server_url != None" would probably help..?

https://github.com/EUDAT-B2SAFE/PYHANDLE/blob/d1b0f2fbe186f47d6909362156a27c675930d675/pyhandle/client/resthandleclient.py#L102

**Comment by SofianeB** [comment]
Fixed by #19 .
