### ISSUE TITLE
Documentation should give import example

### ISSUE THREAD

**Issue by TobiasWeigel** [EUDAT-B2SAFE/PYHANDLE#22]
The section in the docs here

https://eudat-b2safe.github.io/PYHANDLE/pyhandleclientrest.html#general-usage

explains to the first-time user how to get a PyHandle client instance. It is however not clear from where to import PyHandleClient.
E.g., just add a line 
`from pyhandle.handleclient import PyHandleClient`

**Comment by SofianeB** [comment]
This is already mentioned here to the first-time user:
https://eudat-b2safe.github.io/PYHANDLE/pyhandleclient.html#select-a-client

but no problem to add it again.
