### ISSUE TITLE
Python 3.7 support?

### ISSUE THREAD

**Issue by rasvaan** [EUDAT-B2SAFE/PYHANDLE#26]
Hi,

Are there any plans to support Python 3.7? Your setup.py indicates the following Python versions are supported: python_requires='>=2.6,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.6',

Is there anything holding back support for newer Python versions?

I'm working on a python script to upload handle identifiers to SURFsara servers:
https://github.com/Rijksmuseum/handle_upload
At the moment I'm using Python 2.7, which works ok, but I would prefer to migrate to 3.7 at some time.

**Comment by SofianeB** [comment]
Hi @rasvaan at the moment the library is tested on Python 2.7 and 3.5 . There is no concret schedule for a release that supports Python 3.7.

**Comment by TobiasWeigel** [comment]
fixed in https://github.com/EUDAT-B2SAFE/PYHANDLE/commit/67a13bbab115b651a96ed982f3ff0fb2ad13b503
