### ISSUE TITLE
Does not support Python 3.6 and higher

### ISSUE THREAD

**Issue by aquatix** [EUDAT-B2SAFE/PYHANDLE#27]
We are currently implementing the Handle system for our archives so we can request PID's. However, trying to pip install the package, I discovered that only Python 3.5 and lower are supported, while we are running more modern versions.

In your `devel` branch there is support for at least Python 3.7 (Python 3.8 would be really nice). Is it possible to release a new version with these fixes? It would be really appreciated!

**Comment by lakka** [comment]
In the `devel` branch the commit which "adds support for python 3.7" https://github.com/EUDAT-B2SAFE/PYHANDLE/commit/67a13bbab115b651a96ed982f3ff0fb2ad13b503 only changes one line in `setup.py`, so I guess the codebase actually already supports higher versions of Python.

**Comment by aquatix** [comment]
Indeed; I only see a few other really minor changes in https://github.com/EUDAT-B2SAFE/PYHANDLE/compare/devel so maybe this can be merged, and the version on https://pypi.org/ can be updated?

**Comment by merretbuurman** [comment]
Sorry that this was not handled for such a long time. The version fixed by lakka is available on pypi now.

**Comment by aquatix** [comment]
Thanks for that! However, now it supports up to Python 3.7, while it also appears to work on 3.8 and probably also 3.9.

**Comment by aquatix** [comment]
I did notice you're already doing that in the `devel` branch, including docker files for testing, so I guess I'll leave you to it :)

**Comment by merretbuurman** [comment]
Yep, I'm just waiting to test a few more changes I did to then make another release.

**Comment by aquatix** [comment]
Awesome, thanks for taking care of the project!
